---
title: "PSTAT 131 HW 2"
author: "Raymond Lee"
date: '2022-04-07'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
abalone = read.csv("abalone.csv")
```

```{r}
library(tidyverse)
library(tidymodels)
tidymodels_prefer()
```

1. 
```{r}
age = abalone$rings+1.5
abalone["age"] = age
hist(age)
```
Age appears to be slightly skewed right.

2. 
```{r}
set.seed(1114)
abalone_split = initial_split(abalone, prop = .80, strata = age)
abalone_train = training(abalone_split)
abalone_test = testing(abalone_split)
```

3. We should not use rings to predict age because age is simply a transformation of rings. 

```{r}
abalone_recipe = recipe(age ~ type + longest_shell + diameter + height +
                          whole_weight + shucked_weight + viscera_weight +
                          shell_weight, data = abalone_train) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_interact(~ starts_with("type"):shucked_weight) %>%
  step_interact(~ longest_shell:diameter) %>%
  step_interact(~ shucked_weight:shell_weight) %>%
  step_normalize(all_predictors())
```

4. 
```{r}
lm_mod = linear_reg() %>% 
  set_engine("lm")
```

5. 
```{r}
lm_wflow = workflow() %>%
  add_model(lm_mod) %>% 
  add_recipe(abalone_recipe)
```

6. 
```{r}
lm_fit = fit(lm_wflow, abalone_train)

lm_fit %>%
  extract_fit_parsnip() %>%
  tidy()

predict_values = data.frame(type = "F", longest_shell = .5, diameter = .1, height = .3, whole_weight = 4, 
                            shucked_weight = 1, viscera_weight = 2, shell_weight = 1)
prediction = predict(lm_fit, predict_values)
prediction
```
The predicted age of the hypothetical abalone is 23.10256.

7. 
```{r}
library(yardstick)

set = metric_set(rsq, rmse, mae)

predicted_age = predict(lm_fit, abalone_train)
predicted_actual_ages = tibble(bind_cols(abalone_train["age"], predicted_age))
predicted_actual_ages

set(predicted_actual_ages, truth = age, estimate = .pred)
```
The $R^2$ is 0.5570949, the RMSE is 2.1507378, and the MAE is 1.5543719.
About 55.7% of the variability in age can be explained using type, longest_shell,
diameter, height, whole_weight, shucked_weight, viscera_weight, and shell_weight.